// ===================== NEWS FEED =====================
// Reads from news-cache.json generated by GitHub Actions every 15 min
// No CORS, no proxy, no API keys needed in browser — works on all browsers

function formatNewsTime(dateStr) {
  try {
    var d = new Date(dateStr);
    if (isNaN(d.getTime())) return 'Recent';
    var diff = Math.floor((new Date() - d) / 60000);
    if (diff < 1) return 'Just now';
    if (diff < 60) return diff + 'm ago';
    if (diff < 1440) return Math.floor(diff / 60) + 'h ago';
    return Math.floor(diff / 1440) + 'd ago';
  } catch(e) { return 'Recent'; }
}

function renderNewsCard(article) {
  var link = (article.link && article.link.startsWith('http')) ? article.link : '#';
  var color = article.color || 'var(--accent)';
  return '<a href="' + link + '" target="_blank" rel="noopener noreferrer" class="news-card">'
    + '<div class="news-meta">'
    + '<span class="news-badge" style="background:' + color + '22;color:' + color + ';border:1px solid ' + color + '44">' + (article.badge || 'NEWS') + '</span>'
    + '<span class="news-time">' + formatNewsTime(article.publishedAt) + '</span>'
    + (article.source ? '<span class="news-time" style="margin-left:auto">' + article.source + '</span>' : '')
    + '</div>'
    + '<div class="news-title">' + article.title + '</div>'
    + (article.desc ? '<div class="news-desc">' + article.desc + '...</div>' : '')
    + '</a>';
}

async function loadNewsFeed() {
  var hkEl = document.getElementById('news-hk');
  var usEl = document.getElementById('news-us');
  var srcEl = document.getElementById('news-src');
  var lastEl = document.getElementById('news-last-update');

  if (hkEl) hkEl.innerHTML = '<div class="news-loading"><div style="font-size:1.5rem">&#128240;</div><div>Loading headlines...</div></div>';
  if (usEl) usEl.innerHTML = '<div class="news-loading"><div style="font-size:1.5rem">&#128240;</div><div>Loading headlines...</div></div>';
  if (srcEl) { srcEl.textContent = 'Loading...'; srcEl.style.color = 'var(--text-muted)'; }

  try {
    // Add cache-busting param so browser always gets latest file
    var resp = await fetch('news-cache.json?t=' + Date.now(), { signal: AbortSignal.timeout(10000) });
    if (!resp.ok) throw new Error('Cache file not found');
    var data = await resp.json();

    var hkArticles = data.hk || [];
    var usArticles = data.us || [];

    if (hkEl) {
      hkEl.innerHTML = hkArticles.length
        ? hkArticles.map(renderNewsCard).join('')
        : '<div class="news-loading" style="color:var(--down)"><div style="font-size:1.5rem">&#9888;</div><div>No HK news cached yet</div><div style="font-size:0.6rem;margin-top:4px;color:var(--text-faint)">GitHub Actions runs every 15 min</div></div>';
    }
    if (usEl) {
      usEl.innerHTML = usArticles.length
        ? usArticles.map(renderNewsCard).join('')
        : '<div class="news-loading" style="color:var(--down)"><div style="font-size:1.5rem">&#9888;</div><div>No US news cached yet</div><div style="font-size:0.6rem;margin-top:4px;color:var(--text-faint)">GitHub Actions runs every 15 min</div></div>';
    }

    var anyLive = hkArticles.length > 0 || usArticles.length > 0;
    if (srcEl) {
      srcEl.textContent = anyLive ? 'GNews (cached)' : 'Cache empty';
      srcEl.style.color = anyLive ? 'var(--accent)' : 'var(--warn)';
    }
    if (lastEl && data.updated) {
      lastEl.textContent = 'Cached ' + formatNewsTime(data.updated);
    }

  } catch(e) {
    // Cache file doesn't exist yet — first run pending
    if (hkEl) hkEl.innerHTML = '<div class="news-loading" style="color:var(--warn)"><div style="font-size:1.5rem">&#9203;</div><div>First cache run pending</div><div style="font-size:0.6rem;margin-top:4px;color:var(--text-faint)">GitHub Actions will populate in ~15 min</div></div>';
    if (usEl) usEl.innerHTML = '<div class="news-loading" style="color:var(--warn)"><div style="font-size:1.5rem">&#9203;</div><div>First cache run pending</div><div style="font-size:0.6rem;margin-top:4px;color:var(--text-faint)">GitHub Actions will populate in ~15 min</div></div>';
    if (srcEl) { srcEl.textContent = 'Awaiting first cache'; srcEl.style.color = 'var(--warn)'; }
  }

  // Re-check every 5 minutes
  setTimeout(loadNewsFeed, 300000);
}
